# 主导航菜单
main:
  - identifier: Home    # 菜单项唯一标识符
    name: 主页    # 菜单项显示名称
    url: /    # 菜单项链接地址
    weight: 1    # 菜单项排序权重（数字越小越靠前）
    params:
      icon: home

  - identifier: Search
    name: 搜索
    url: /search/
    weight: 2
    params:
      icon: search

  - identifier: Archives
    name: 文章
    url: /archives/
    weight: 3
    params:
      icon: archives

  - identifier: Links
    name: 友链
    url: /links/
    weight: 4
    params:
      icon: link

  - identifier: About
    name: 关于
    url: /about/
    weight: 5
    params:
      icon: user

# 社交媒体链接
social:
  - identifier: github
    name: GitHub
    url: https://github.com/bookyzhou
    weight: 1
    params:
      icon: brand-github

  - identifier: bilibili
    name: Bilibili
    url: https://space.bilibili.com/629603804
    weight: 2
    params:
      icon: brand-bilibili

  - identifier: zhihu
    name: Zhihu
    url: https://www.zhihu.com/people/zhou-yi-heng-88-37
    weight: 3
    params:
      icon: brand-zhihu

  - identifier: mail
    name: Mail
    url: mailto:zhouyiheng@mail.ustc.edu.cn
    weight: 4
    params:
      icon: mail

  - identifier: rss
    name: RSS
    url: /index.xml
    weight: 5
    params:
      icon: rss
